language: node_js
node_js:
  - "14.0"
branches:
  only:
    - main
before_script:
  - npm install -g @angular/cli
  - npm install -g protractor
script:
  - npm install
  - npm run coverage
  - npm run test